<?php

namespace Ojstr\WorkflowBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WorkflowStepRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkflowStepRoleRepository extends EntityRepository
{
}
