<?php

namespace Ojstr\WorkflowBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WorkflowStepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkflowStepRepository extends EntityRepository
{
}
