<?php

namespace Ojstr\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AttorneyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttorneyRepository extends EntityRepository {

}
