<?php

namespace Ojstr\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserJournalRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserJournalRoleRepository extends EntityRepository
{
}
