<?php

namespace Ojstr\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Session\Session;

/**
 * UserJournalRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserJournalRoleRepository extends EntityRepository {

    /**
     * get user list of users a journal with journal_id
     * @param integer $journal_id
     */
    public function getUsers($journal_id) {
        $em = $this->getManager();
        $user_journal_roles = $em->getRepository('OjstrUserBundle:UserJournalRole')->findByJournalId($journal_id);
        $entites = array();
        if (!is_array($user_journal_roles)) {
            return FALSE;
        }
        foreach ($user_journal_roles as $item) {
            $entites[] = $item->getUser();
        }
        return $entites;
    }

   
    

}
