<?php

namespace Vipa\JournalBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Vipa\CoreBundle\Entity\FindTrait;

/**
 * JournalSubmissionFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalSubmissionFileRepository extends EntityRepository
{
}
