<?php

namespace Vipa\JournalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublisherRepository extends EntityRepository
{
    /**
     * @param bool $all
     * @return array
     */
    public function getAllWithDefaultTranslation($all = false)
    {
        $qb = $this->createQueryBuilder("i");
        if (!$all) {
            $qb->andWhere($qb->expr()->eq('i.status', 1));
        }

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
