<?php

namespace Vipa\JournalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PublisherDesignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublisherDesignRepository extends EntityRepository
{
}
