<?php

namespace Ojstr\JournalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CitationSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CitationSettingRepository extends EntityRepository
{
}
