<?php

namespace Ojstr\JournalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JournalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalRepository extends EntityRepository {

    /**
     * get user list of users a journal with journal_id
     * @param integer $user_id
     */
    public function getUsers($user_id) {
        $em = $this->getEntityManager();
        $user_journal_roles = $em->getRepository('OjstrUserBundle:UserJournalRole')->findByUserId($user_id);
        $entites = array();
        if (is_array($user_journal_roles)) {
            return FALSE;
        }
        foreach ($user_journal_roles as $item) {
            $entites[] = $item->getUser();
        }
        return $entites;
    }

    /**
     * get user list of journals of a user with user_id
     * @param integer $journal_id
     * @return boolean|array
     */
    public function getJournals($journal_id) {
        $em = $this->getEntityManager();
        //$user = $em->getRepository('OjstrUserBundle:User')->findOneById($user_id);
        $user_journal_roles = $em->getRepository('OjstrUserBundle:UserJournalRole')->findByJournalId($journal_id);
        $entites = array();
        if (is_array($user_journal_roles)) {
            return FALSE;
        }
        foreach ($user_journal_roles as $item) {
            $entites[] = $item->getJournal();
        }
        return $entites;
    }

}
