<?php

namespace Ojs\UserBundle\Entity;

/**
 * MultipleMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MultipleMailRepository extends \Doctrine\ORM\EntityRepository
{
}
