<?php

namespace Ojs\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserArticleRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserArticleRoleRepository extends EntityRepository
{
}
