<?php

namespace Ojs\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Ojs\JournalBundle\Entity\Journal;

/**
 * UserJournalRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserJournalRoleRepository extends EntityRepository
{
    /**
     * get user list of users a journal with journal_id
     * @param $journal_id
     * @param  bool       $grouppedByRole
     * @return array|bool
     */
    public function getUsers($journal_id, $grouppedByRole = false)
    {
        $user_journal_roles = $this->getEntityManager()->getRepository('OjsUserBundle:UserJournalRole')->findByJournalId($journal_id);
        $entites = array();
        if (!is_array($user_journal_roles)) {
            return false;
        }
        foreach ($user_journal_roles as $item) {
            $entites[] = $item->getUser();
        }

        if (!$grouppedByRole) {
            return $entites;
        }

        $users = [];
        foreach ($entites as $user) {
            /** @var User $user */
            foreach ($user->getRoles() as $role) {
                /** @var Role $role */
                if ($role->getIsSystemRole()) {
                    continue;
                }
                $users[$role->getName()][] = $user;
            }
        }

        return $users;
    }
    /**
     * @param $user_id
     * @param  bool  $onlyJournalIds
     * @return array
     */
    public function userJournalsWithRoles($user_id, $onlyJournalIds = false)
    {
        $data = $this->getEntityManager()->createQuery(
            'SELECT u FROM OjsUserBundle:UserJournalRole u WHERE u.userId = :user_id '
        )->setParameter('user_id', $user_id)->getResult();
        $entities = array();
        if ($data) {
            foreach ($data as $item) {
                $entities[$item->getJournalId()]['journal'] = $onlyJournalIds ? $item->getJournal()->getId() : $item->getJournal();
                $entities[$item->getJournalId()]['roles'][] = $item->getRole();
            }
        }

        return $entities;
    }
    /**
     * @param int $user_id Use null for all
     * @return array Array structrue: [user_id][journal_id]['roles']
     */
    public function getUsersWithRoles($user_id = null)
    {
        $array = array();

        if ($user_id === null)
            $roles = $this->findAll();
        else
            $roles = $this->findByUserId($user_id);

        foreach ($roles as $role) {
            $array[$role->getUserId()]['user'] = $role->getUser();
            $array[$role->getUserId()]['journals'][$role->getJournalId()]['journal'] = $role->getJournal();
            $array[$role->getUserId()]['journals'][$role->getJournalId()]['roles'][] = $role->getRole();
        }

        return $array;
    }
    /**
     * @param string|array $role
     * @return UserJournalRole[]
     */
    public function findAllByJournalRole($role)
    {
        $query = $this->createQueryBuilder('ujr')
            ->select('ujr')
            ->join('ujr.user', 'u')
            ->join('ujr.role', 'r')
            ->join('ujr.journal', 'j');
        if(is_array($role)) {
            $query = $query->where('r.role IN (:role)');
        }
        else {
            $query = $query->where('r.role = :role');
        }
        $query = $query
            ->setParameter('role', $role)
            ->getQuery();
        return $query;
    }

    /**
     * @param Journal $journal
     * @param User $user
     * @return array
     */
    public function findAllByJournalAndUser(Journal $journal, User $user)
    {
        /** @var UserJournalRole[] $query */
        $query = $this->createQueryBuilder('ujr')
            ->andWhere('ujr.user = :user')
            ->andWhere('ujr.journal = :journal')
            ->setParameter('journal', $journal)
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
        $roles = array();
        if($query) {
            foreach($query as $userJournalRole) {
                $roles[] = $userJournalRole->getRole()->getRole();
            }
        }
        return $roles;
    }
}
