<?php

namespace Ojs\AdminBundle\Entity;

/**
 * AdminAnnouncementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminAnnouncementRepository extends \Doctrine\ORM\EntityRepository
{
}
