<?php

namespace Ojs\AdminBundle\Entity;

/**
 * AdminPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminPageRepository extends \Doctrine\ORM\EntityRepository
{
}
