<?php

namespace Ojs\AdminBundle\Entity;

/**
 * AdminPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminPostRepository extends \Doctrine\ORM\EntityRepository
{
}
