<?php

namespace Ojs\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InstitutionManagersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitutionManagersRepository extends EntityRepository
{
}
