<?php

namespace Ojs\AdminBundle\Entity;

/**
 * SystemSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemSettingRepository extends \Doctrine\ORM\EntityRepository
{
}
