<?php

namespace Ojs\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SystemSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemSettingRepository extends EntityRepository
{
}
