<?php

namespace Ojs\WorkflowBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ArticlereviewStepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlereviewStepRepository extends DocumentRepository
{
}