<?php

namespace Ojs\JournalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleFileRepository extends EntityRepository {

    /**
     * Get Article full text file. 
     * @param  integer $articleId
     * @return ArticleFile
     * @throws NoResultException
     */
    public function getArticleFullTextFiles($articleId)
    {
        $q = $this
                ->createQueryBuilder('a')
                ->select('a')
                ->where('a.articleId = :article_id AND a.type= 0')
                ->setParameter('article_id', $articleId)
                ->getQuery();
        try {
            // The Query::getResuşt() method throws an exception
            // if there is no record matching the criteria.
            return $q->getResult();
        } catch (NoResultException $e) {
            $message = sprintf('There is no full text file for this article.');
            throw new UsernameNotFoundException($message, 0, $e);
        }
    }

}
