<?php

namespace Ojs\JournalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends EntityRepository
{

    public function getByIds(array $data)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->where(
            $qb->expr()->in('a.id', ':data')
        )
            ->setParameter('data', $data);
        return $qb->getQuery()->getResult();
    }

}
