<?php

namespace Ojs\JournalBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitutionRepository extends EntityRepository
{
    /**
     * @param bool $all
     * @return array
     */
    public function getAllWithDefaultTranslation($all = false)
    {
        $qb = $this->createQueryBuilder("i");
        if($all) {
            $qb->andWhere('i.verified = :verified')
                ->setParameter('verified', true);
        }
        $qb->andWhere(
            $qb->expr()->eq('i.status',1)
        );


        $query = $qb->getQuery();

        $query->setHint(
            Query::HINT_CUSTOM_OUTPUT_WALKER,
            'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
        );
        return $query->getResult();
    }
}
