<?php

namespace Ojs\JournalBundle\Entity;

/**
 * JournalPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalPostRepository extends \Doctrine\ORM\EntityRepository
{
}
