<?php

namespace Ojs\JournalBundle\Entity;

/**
 * JournalUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalUserRepository extends \Doctrine\ORM\EntityRepository
{
}
