<?php

namespace Ojs\JournalBundle\Entity;

/**
 * JournalPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalPageRepository extends \Doctrine\ORM\EntityRepository
{
}
