<?php

namespace Ojs\JournalBundle\Entity;

/**
 * JournalAnnouncementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalAnnouncementRepository extends \Doctrine\ORM\EntityRepository
{
}
