<?php

namespace Ojs\JournalBundle\Entity;

/**
 * PersonTitleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonTitleRepository extends \Doctrine\ORM\EntityRepository
{
}
