<?php

namespace Ojs\JournalBundle\Entity;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectRepository extends NestedTreeRepository {

    public function getByInstitution($institution) {
        $qb = $this->createQueryBuilder('s');
        $qb
                ->join('s.journals', 'j', 'WITH')
                ->join('j.institution', 'i', 'WITH', 'i.slug=:institution')
                ->setParameter('institution', $institution)
        ;
        return $qb->getQuery()->getResult();
    }

    /**
     * @param array $data
     * @return array
     */
    public function getByIds(array $data)
    {
        $qb = $this->createQueryBuilder('j');
        $qb->where(
            $qb->expr()->in('j.id', ':data')
        )
            ->setParameter('data', $data);
        return $qb->getQuery()->getResult();
    }

}
