<?php

namespace Ojs\JournalBundle\Entity;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectRepository extends \Gedmo\Tree\Entity\Repository\NestedTreeRepository {

    public function getByInstitution($institution) {
        $qb = $this->createQueryBuilder('s');
        $qb
                ->join('s.journals', 'j', 'WITH')
                ->join('j.institution', 'i', 'WITH', 'i.slug=:institution')
                ->setParameter('institution', $institution)
        ;
        return $qb->getQuery()->getResult();
    }

}
