<?php

namespace Ojs\JournalBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Ojs\CoreBundle\Entity\FindTrait;

/**
 * SubmissionChecklistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubmissionChecklistRepository extends EntityRepository
{
}
