<?php

namespace Ojs\CliBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CliLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CliLogRepository extends EntityRepository
{
}
