<?php

namespace Vipa\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MultipleMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MultipleMailRepository extends EntityRepository
{
}
