<?php

namespace Ojs\ReportBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ObjectDownloadsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectDownloadsRepository extends DocumentRepository
{
    /**
     * @param  \DateTime                              $date
     * @param $entity
     * @param $id
     * @return mixed
     * @throws \Doctrine\ODM\MongoDB\MongoDBException
     */
    public function getAfterFrom(\DateTime $date, $entity, $id)
    {
        $qb = $this->createQueryBuilder();
        $qb->select(["id"]);
        $qb->field('logDate')->gte($date)
            ->field('entity')->equals($entity)
            ->field('objectId')->equals($id);

        return $qb->getQuery()->execute();
    }
}
