<?php

namespace Vipa\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdminJournalThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminJournalThemeRepository extends EntityRepository
{
}
