<?php

namespace Vipa\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PublisherManagersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublisherManagersRepository extends EntityRepository
{
}
