<?php

namespace Vipa\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Vipa\CoreBundle\Entity\FindTrait;

/**
 * SystemSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemSettingRepository extends EntityRepository
{
    use FindTrait;
}
