<?php

namespace Ojs\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlockLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockLinkRepository extends EntityRepository
{

}
