<?php

namespace Ojs\AnalyticsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleStatisticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleStatisticRepository extends EntityRepository
{
}
