<?php

namespace Ojs\UserBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * AnonymUserTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnonymUserTokenRepository extends DocumentRepository
{
}