./citationParseBulk  "Siegel R, Naishadham D, Jemal A (2013) Cancer statistics, 2013. CA: a cancer journal for clinicians 63:11-30.
Quinn M, Babb P, Jones J, Allen E(1999) Effect of screening on incidence of and mortality from cancer of cervix in England: evaluation based on routinely collected statistics. BMJ 318:904-908.
Walboomers JM, Jacobs MV, Manos MM, Bosch FX, Kummer JA, Shah KV, Snijders PJ, Peto J, Meijer CJ, Munoz N (1999)Human papillomavirus is a necessary cause of invasive cervical cancer worldwide. The Journal of pathology 189:12-19.
A human papillomavirus vaccine (2006). The Medical letter on drugs and therapeutics 48:65-66.
Cervarix--a second HPV vaccine (2010). The Medical letter on drugs and therapeutics 52:37-38.
Faeh D, William J, Yerly P, Paccaud F, Bovet P(2007) Diabetes and pre-diabetes are associated with cardiovascular risk factors and carotid/femoral intima-media thickness independently of markers of insulin resistance and adiposity. Cardiovascular diabetology 6:32.
Paavonen J, Naud P, Salmeron J, Wheeler CM, Chow SN, Apter D, Kitchener H, Castellsague X, Teixeira JC, Skinner SR et al(2009) Efficacy of human papillomavirus (HPV)-16/18 AS04-adjuvanted vaccine against cervical infection and precancer caused by oncogenic HPV types (PATRICIA): final analysis of a double-blind, randomised study in young women. Lancet 374:301-314.
Saslow D, Castle PE, Cox JT, Davey DD, Einstein MH, Ferris DG, Goldie SJ, Harper DM, Kinney W, Moscicki AB et al.(2007) American Cancer Society Guideline for human papillomavirus (HPV) vaccine use to prevent cervical cancer and its precursors. CA: a cancer journal for clinicians, 57:7-28.
Baseman JG, Koutsky LA (2005) The epidemiology of human papillomavirus infections. Journal of clinical virology : the official publication of the Pan American Society for Clinical Virology, 32 Suppl 1:S16-24.
Koutsky LA, Galloway DA, Holmes KK(1988) Epidemiology of genital human papillomavirus infection. Epidemiologic reviews 10:122-163.
Roset Bahmanyar E, Paavonen J, Naud P, Salmeron J, Chow SN, Apter D, Kitchener H, Castellsague X, Teixeira JC, Skinner SR et al (2012)Prevalence and risk factors for cervical HPV infection and abnormalities in young adult women at enrolment in the multinational PATRICIA trial. Gynecologic oncology , 127:440-450.
Rodriguez AC, Schiffman M, Herrero R, Wacholder S, Hildesheim A, Castle PE, Solomon D, Burk R(2008)Rapid clearance of human papillomavirus and implications for clinical focus on persistent infections. Journal of the National Cancer Institute , 100:513-517.
Trottier H, Franco EL(2006) The epidemiology of genital human papillomavirus infection. Vaccine, 24 Suppl 1:S1-15.
Klug SJ, Hukelmann M, Blettner M(2008) Knowledge about infection with human papillomavirus: a systematic review. Preventive medicine, 46:87-98.
Durusoy R, Yamazhan M, Tasbakan MI, Ergin I, Aysin M, Pullukcu H, Yamazhan T(2010)HPV vaccine awareness and willingness of first-year students entering university in Western Turkey. Asian Pacific journal of cancer prevention : APJCP , 11:1695-1701.
Blodt S, Holmberg C, Muller-Nordhorn J, Rieckmann N(2012) Human Papillomavirus awareness, knowledge and vaccine acceptance: a survey among 18-25 year old male and female vocational school students in Berlin, Germany. European journal of public health, 22:808-813.
Ozyer S, Uzunlar O, Ozler S, Kaymak O, Baser E, Gungor T, Mollamahmutoglu L(2013) Awareness of Turkish female adolescents and young women about HPV and their attitudes towards HPV vaccination. Asian Pacific journal of cancer prevention : APJCP, 14:4877-4881.
Laz TH, Rahman M, Berenson AB(2013) Human papillomavirus vaccine uptake among 18- to 26-year-old women in the United States: National Health Interview Survey, 2010. Cancer, 119:1386-1392.
Al-Naggar RA, Bobryshev YV, Al-Jashamy K, Al-Musli M(2012)Practice of HPV vaccine and associated factors among school girls in Melaka, Malaysia. Asian Pacific journal of cancer prevention : APJCP, 13:3835-3840.
Kahn JA, Rosenthal SL, Hamann T, Bernstein DI(2003) Attitudes about human papillomavirus vaccine in young women. International journal of STD & AIDS , 14:300-306.
Chan ZC, Chan TS, Ng KK, Wong ML(2012) A systematic review of literature about women's knowledge and attitudes toward human papillomavirus (HPV) vaccination. Public Health Nurs, 29:481-489.
Blackman E, Thurman N, Halliday D, Butler R, Francis D, Joseph M, Thompson J, Akers A, Andraos-Selim C, Bondzi C et at (2013)Multicenter study of human papillomavirus and the human papillomavirus vaccine: knowledge and attitudes among people of African descent. Infectious diseases in obstetrics and gynecology , 2013:428582."
