<?php

namespace Ojs\CmsBundle\Entity;

/**
 * AnnouncementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnouncementRepository extends \Doctrine\ORM\EntityRepository
{
}
